server:
  port: 8080

spring:
  application:
    name: backend-sight

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}