apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-sight-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-sight
  template:
    metadata:
      labels:
        app: backend-sight
    spec:
      containers:
        - name: backend-sight
          image: earseo/backend-sight:0.0.1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: backend-configmap
              readOnly: true
            - mountPath: /etc/secret
              name: backend-secret
              readOnly: true
      volumes:
        - name: backend-configmap
          configMap:
            name: backend-configmap
            items:
              - key: application-dev.yaml
                path: application-dev.yaml
        - name: backend-secret
          secret:
            secretName: backend-secret
            items:
              - key: application-secret.yaml
                path: application-secret.yaml